networks:
  intra_net:
    driver: bridge
  external_net:
    driver: bridge

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always

    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: "${DBMYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - intra_net

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - intra_net
    depends_on:
      - service1
      - service2

  service1:
    container_name: service1
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: "db"
      DB_PORT: 3306
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${DBMYSQL_PASSWORD}"
      DB_NAME: "${MYSQL_DATABASE}"
    networks:
      - intra_net

  service2:
    container_name: service2
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8001"
    environment:
      DB_HOST: "db"
      DB_PORT: 3306
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${DBMYSQL_PASSWORD}"
      DB_NAME: "${MYSQL_DATABASE}"
    networks:
      - intra_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm start"
    depends_on:
      - nginx
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_API_URL: "${REACT_APP_API_URL}"
    networks:
      - external_net

volumes:
  mysql_data: {}
