# Docker file for django-rest aplicattion backend
FROM python:3.10.0


# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential
# Set work directory
WORKDIR /app

# Copy project
COPY . /app/

# Install dependencies
RUN pip install -r requirements.txt