# Generated by Django 4.2.11 on 2024-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigaa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
