# Generated by Django 4.2.11 on 2024-05-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_refeicao', models.CharField(choices=[('N', 'Normal'), ('V', 'Vegetariana'), ('A', 'Acompanhamento')], default='N', max_length=1)),
                ('nome_refeicao', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('A', 'Almoço'), ('J', 'Jantar')], default='A', max_length=1)),
                ('data', models.DateField(verbose_name='Data')),
                ('alimentos', models.ManyToManyField(related_name='cardapios', to='refeicoes.alimento')),
            ],
            options={
                'verbose_name': 'Cardapio',
                'verbose_name_plural': 'Cardapios',
                'ordering': ['data'],
            },
        ),
    ]
