# Generated by Django 4.2.11 on 2024-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio_img/%Y/%m/%d', verbose_name='Imagem'),
        ),
        migrations.AlterUniqueTogether(
            name='cardapio',
            unique_together={('data', 'tipo')},
        ),
    ]
